select * from Customer1@site_link1;
commit;
select * from Customer2@site_link2;
commit;
select * from Admin1@site_link1;
commit;
select * from Admin2@site_link2;
commit;
select * from RoomDetails1@site_link1;
commit;
select * from RoomDetails2@site_link2;
commit;
select * from Reservation1@site_link1;
commit;
select * from Reservation2@site_link2;
commit;
select * from Employee1@site_link1;
commit;
select * from Employee2@site_link2;
commit;
select * from Food1@site_link1;
commit;
select * from Food2@site_link2;
commit;
select * from Bill1@site_link1;
commit;
select * from Bill2@site_link2;
commit;